Simple test for DurableStateSourceProvider, failing since in-mem does not implement query.
java.lang.ClassCastException: akka.persistence.state.inmem.scaladsl.InmemDurableStateStore cannot be cast to akka.persistence.query.scaladsl.DurableStateStoreQuery